name: Build For Windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch_name: x86_64
            runner: windows-latest
          - arch_name: arm64
            runner: windows-11-arm

    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: Checkout builder
        uses: actions/checkout@v4
        with:
          path: builder

      - name: Checkout ethos
        uses: actions/checkout@v4
        with:
          repository: AmanCode22/ethos-lang
          path: ethos

      - name: Checkout Forge
        uses: actions/checkout@v4
        with:
          repository: AmanCode22/forge
          path: forge

      - name: Install python
        uses: actions/setup-python@v5
        

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ethos/requirements.txt
          pip install nuitka

      - name: Build ethos
        run: |
          python -m nuitka --assume-yes-for-downloads --standalone ethos/main.py --output-filename=ethos.exe --output-dir=build_ethos
          Rename-Item -Path "build_ethos\main.dist" -NewName "ethos.dist"

      - name: Build forge
        run: |
          python -m nuitka --assume-yes-for-downloads --standalone forge/main.py --output-filename=forge.exe --output-dir=build_forge
          Rename-Item -Path "build_forge\main.dist" -NewName "forge.dist"

      - name: Build windows installer
        #
        run: |
          iscc /DAppArch=${{ matrix.arch_name }} builder/windows/ethos_script.iss

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ethos-windows-installer-${{ matrix.arch_name }}
          path: builder/windows/Output/Ethos-windows-installer-${{ matrix.arch_name }}.exe
