name: Build For Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v6
        with:
          path: builder
      - name: Checkout ethos
        uses: actions/checkout@v6
        with:
          repository: AmanCode22/ethos-lang
          path: ethos
      - name: Checkout Forge
        uses: actions/checkout@v6
        with:
          repository: AmanCode22/forge
          path: forge
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r ethos/requirements.txt
      - name: Build ethos
        run: |
          python -m nuitka --assume-yes-for-downloads --onefile ethos/main.py --output-filename=ethos.exe
      - name: Build forge
        run: |
          python -m nuitka --assume-yes-for-downloads --onefile forge/main.py --output-filename=forge.exe
      - name: Debug paths
        run: |
          echo "=== Workspace root ==="
          dir D:\a\ethos-builder\ethos-builder\
          echo "=== builder/windows ==="
          dir builder\windows\
          echo "=== Does ethos.exe exist? ==="
          Test-Path "ethos.exe"
          echo "=== Does forge.exe exist? ==="
          Test-Path "forge.exe"
      - name: Build windows installer
        run: |
          iscc builder/windows/ethos.iss
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v6
        with:
          name: Ethos-v0.2-windows-installer.exe
          path: builder/windows/Output/Ethos-v0.2-windows-installer.exe
      - name: Upload ethos compiled exe
        uses: actions/upload-artifact@v6
        with:
          name: ethos.exe
          path: ethos.exe
      - name: Upload forge compiled exe
        uses: actions/upload-artifact@v6
        with:
          name: forge.exe
          path: forge.exe
